FROM docker.io/library/golang as firstbuild
COPY . /kcdkerala
WORKDIR /kcdkerala
RUN go build main.go
ENTRYPOINT /kcdkerala/main
FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root
COPY --from=firstbuild /kcdkerala/main .
CMD ["./main"]
